#############################################################################
# Makefile for building: build/bin/FEBioStudioUpdater
# Generated by qmake (3.1) (Qt 5.14.1)
# Project:  FEBioStudioUpdater.pro
# Template: app
# Command: /home/mherron/Resources/Qt/5.14.1/gcc_64/bin/qmake -o Makefile FEBioStudioUpdater.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DLINUX -DQT_OPENGL_LIB -DQT_CHARTS_LIB -DQT_WEBENGINEWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -w -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++14 -O0 -g -std=gnu++1y -w -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../FEBioStudio -isystem /usr/include/libdrm -I../../Resources/Qt/5.14.1/gcc_64/include -I../../Resources/Qt/5.14.1/gcc_64/include/QtOpenGL -I../../Resources/Qt/5.14.1/gcc_64/include/QtCharts -I../../Resources/Qt/5.14.1/gcc_64/include/QtWebEngineWidgets -I../../Resources/Qt/5.14.1/gcc_64/include/QtPrintSupport -I../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets -I../../Resources/Qt/5.14.1/gcc_64/include/QtWebEngineCore -I../../Resources/Qt/5.14.1/gcc_64/include/QtQuick -I../../Resources/Qt/5.14.1/gcc_64/include/QtGui -I../../Resources/Qt/5.14.1/gcc_64/include/QtQmlModels -I../../Resources/Qt/5.14.1/gcc_64/include/QtWebChannel -I../../Resources/Qt/5.14.1/gcc_64/include/QtQml -I../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork -I../../Resources/Qt/5.14.1/gcc_64/include/QtPositioning -I../../Resources/Qt/5.14.1/gcc_64/include/QtCore -I. -I../../Resources/Qt/5.14.1/gcc_64/mkspecs/linux-g++
QMAKE         = /home/mherron/Resources/Qt/5.14.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/mherron/Resources/Qt/5.14.1/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/mherron/Resources/Qt/5.14.1/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = FEBioStudioUpdater1.0.0
DISTDIR = /home/mherron/Projects/FEBioStudioUpdater/.tmp/FEBioStudioUpdater1.0.0
LINK          = g++
LFLAGS        = -static-libstdc++ -static-libgcc -Wl,-rpath,\$$ORIGIN/../lib -Wl,-rpath,/home/mherron/Resources/Qt/5.14.1/gcc_64/lib -Wl,-rpath-link,/home/mherron/Resources/Qt/5.14.1/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/mherron/Projects/FEBioStudio/build/lib -Wl,--start-group -lmathlib -lfscore -lxml -Wl,--end-group -lGL /home/mherron/Resources/Qt/5.14.1/gcc_64/lib/libQt5OpenGL.so /home/mherron/Resources/Qt/5.14.1/gcc_64/lib/libQt5Charts.so /home/mherron/Resources/Qt/5.14.1/gcc_64/lib/libQt5WebEngineWidgets.so /home/mherron/Resources/Qt/5.14.1/gcc_64/lib/libQt5PrintSupport.so /home/mherron/Resources/Qt/5.14.1/gcc_64/lib/libQt5Widgets.so /home/mherron/Resources/Qt/5.14.1/gcc_64/lib/libQt5WebEngineCore.so /home/mherron/Resources/Qt/5.14.1/gcc_64/lib/libQt5Quick.so /home/mherron/Resources/Qt/5.14.1/gcc_64/lib/libQt5Gui.so /home/mherron/Resources/Qt/5.14.1/gcc_64/lib/libQt5QmlModels.so /home/mherron/Resources/Qt/5.14.1/gcc_64/lib/libQt5WebChannel.so /home/mherron/Resources/Qt/5.14.1/gcc_64/lib/libQt5Qml.so /home/mherron/Resources/Qt/5.14.1/gcc_64/lib/libQt5Network.so /home/mherron/Resources/Qt/5.14.1/gcc_64/lib/libQt5Positioning.so /home/mherron/Resources/Qt/5.14.1/gcc_64/lib/libQt5Core.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = FEBioStudioUpdater.cpp \
		MainWindow.cpp moc_MainWindow.cpp
OBJECTS       = FEBioStudioUpdater.o \
		MainWindow.o \
		moc_MainWindow.o
DIST          = ../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/unix.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/linux.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/sanitize.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/qconfig.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/toolchain.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/default_post.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/warn_off.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/qt.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/resources_functions.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/resources.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/moc.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/uic.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/file_copies.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/yacc.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/lex.prf \
		FEBioStudioUpdater.pro FEBioStudioUpdater.h \
		MainWindow.h \
		moc_predefs.h FEBioStudioUpdater.cpp \
		MainWindow.cpp
QMAKE_TARGET  = FEBioStudioUpdater
DESTDIR       = build/bin/
TARGET        = build/bin/FEBioStudioUpdater


first: all
####### Build rules

build/bin/FEBioStudioUpdater:  $(OBJECTS)  
	@test -d build/bin/ || mkdir -p build/bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FEBioStudioUpdater.pro ../../Resources/Qt/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf ../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/unix.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/linux.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/sanitize.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/qconfig.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/toolchain.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/default_post.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/warn_off.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/qt.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/resources_functions.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/resources.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/moc.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/uic.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/file_copies.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/yacc.prf \
		../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/lex.prf \
		FEBioStudioUpdater.pro
	$(QMAKE) -o Makefile FEBioStudioUpdater.pro
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/spec_pre.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/unix.conf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/linux.conf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/sanitize.conf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/gcc-base.conf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/g++-base.conf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/common/g++-unix.conf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/qconfig.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/qt_functions.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/qt_config.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/toolchain.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/default_pre.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/resolve_config.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/default_post.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/warn_off.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/unix/opengl.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/qt.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/resources_functions.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/resources.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/moc.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/uic.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/unix/thread.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/qmake_use.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/file_copies.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/exceptions.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/yacc.prf:
../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/lex.prf:
FEBioStudioUpdater.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile FEBioStudioUpdater.pro

qmake_all: FORCE


all: Makefile build/bin/FEBioStudioUpdater

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents FEBioStudioUpdater.h MainWindow.h moc_predefs.h $(DISTDIR)/
	$(COPY_FILE) --parents FEBioStudioUpdater.cpp MainWindow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++14 -O0 -g -std=gnu++1y -w -dM -E -o moc_predefs.h ../../Resources/Qt/5.14.1/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp
moc_MainWindow.cpp: MainWindow.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QWizard \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qwizard.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtguiglobal.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qglobal.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qconfig.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qtcore-config.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsysinfo.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qlogging.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qflags.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qatomic.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qmutex.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qnumeric.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qversiontagging.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtgui-config.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qdialog.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qwidget.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qnamespace.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qobject.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstring.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qchar.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qbytearray.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qrefcount.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qarraydata.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringliteral.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringview.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qlist.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qalgorithms.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qiterator.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qpair.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qvector.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qpoint.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringlist.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qregexp.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcoreevent.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qmetatype.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qobject_impl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qmargins.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qrect.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsize.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpalette.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qcolor.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qrgb.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qrgba64.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qbrush.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qmatrix.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpolygon.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qregion.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qdatastream.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qiodevice.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qline.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtransform.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpainterpath.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qimage.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpixelformat.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpixmap.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qshareddata.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qhash.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qfont.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qfontinfo.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qcursor.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qkeysequence.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qevent.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qvariant.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qmap.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qdebug.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qtextstream.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qlocale.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qset.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qurl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qurlquery.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qfile.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qfiledevice.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qvector2d.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtouchdevice.h \
		moc_predefs.h \
		../../Resources/Qt/5.14.1/gcc_64/bin/moc
	/home/mherron/Resources/Qt/5.14.1/gcc_64/bin/moc $(DEFINES) --include /home/mherron/Projects/FEBioStudioUpdater/moc_predefs.h -I/home/mherron/Resources/Qt/5.14.1/gcc_64/mkspecs/linux-g++ -I/home/mherron/Projects/FEBioStudioUpdater -I/home/mherron/Projects/FEBioStudioUpdater -I/home/mherron/Projects/FEBioStudio -I/usr/include/libdrm -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include/QtOpenGL -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include/QtCharts -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include/QtWebEngineWidgets -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include/QtPrintSupport -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include/QtWidgets -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include/QtWebEngineCore -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include/QtQuick -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include/QtGui -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include/QtQmlModels -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include/QtWebChannel -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include/QtQml -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include/QtNetwork -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include/QtPositioning -I/home/mherron/Resources/Qt/5.14.1/gcc_64/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include MainWindow.h -o moc_MainWindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

FEBioStudioUpdater.o: FEBioStudioUpdater.cpp ../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QApplication \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qapplication.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtguiglobal.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qglobal.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qconfig.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qtcore-config.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsysinfo.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qlogging.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qflags.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qatomic.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qmutex.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qnumeric.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qversiontagging.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtgui-config.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstring.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qchar.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qbytearray.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qrefcount.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qnamespace.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qarraydata.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringliteral.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringview.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qobject.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qlist.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qalgorithms.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qiterator.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qpair.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qvector.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qpoint.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringlist.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qregexp.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcoreevent.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qmetatype.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qobject_impl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qeventloop.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsize.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qmargins.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qcursor.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qwidget.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qrect.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpalette.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qcolor.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qrgb.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qrgba64.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qbrush.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qmatrix.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpolygon.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qregion.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qdatastream.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qiodevice.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qline.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtransform.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpainterpath.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qimage.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpixelformat.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpixmap.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qshareddata.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qhash.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qfont.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qfontinfo.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qkeysequence.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qevent.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qvariant.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qmap.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qdebug.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qtextstream.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qlocale.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qset.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qurl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qurlquery.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qfile.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qfiledevice.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qvector2d.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qguiapplication.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qinputmethod.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/QIcon \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qicon.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QString \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QFileInfo \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qfileinfo.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QFileDialog \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qfiledialog.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qdir.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qdialog.h \
		MainWindow.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QWizard \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qwizard.h \
		FEBioStudioUpdater.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QSplashScreen \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qsplashscreen.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QDebug \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QFile \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QDir \
		../FEBioStudio/XML/XMLReader.h \
		../FEBioStudio/MathLib/math3d.h \
		../FEBioStudio/MathLib/mat3d.h \
		../FEBioStudio/MathLib/mat3d.hpp \
		../FEBioStudio/FSCore/color.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FEBioStudioUpdater.o FEBioStudioUpdater.cpp

MainWindow.o: MainWindow.cpp ../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QApplication \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qapplication.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtguiglobal.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qglobal.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qconfig.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qtcore-config.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsysinfo.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qlogging.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qflags.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qatomic.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qmutex.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qnumeric.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qversiontagging.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtgui-config.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstring.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qchar.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qbytearray.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qrefcount.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qnamespace.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qarraydata.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringliteral.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringview.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qobject.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qlist.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qalgorithms.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qiterator.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qpair.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qvector.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qpoint.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringlist.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qregexp.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcoreevent.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qmetatype.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qobject_impl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qeventloop.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsize.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qmargins.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qcursor.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qwidget.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qrect.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpalette.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qcolor.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qrgb.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qrgba64.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qbrush.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qmatrix.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpolygon.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qregion.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qdatastream.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qiodevice.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qline.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtransform.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpainterpath.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qimage.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpixelformat.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpixmap.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qshareddata.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qhash.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qfont.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qfontinfo.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qkeysequence.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qevent.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qvariant.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qmap.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qdebug.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qtextstream.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qlocale.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qset.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qurl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qurlquery.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qfile.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qfiledevice.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qvector2d.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qguiapplication.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qinputmethod.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QDialog \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qdialog.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QDialogButtonBox \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qdialogbuttonbox.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QWizardPage \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qwizard.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QLabel \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qlabel.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qframe.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QAbstractButton \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qicon.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QMessageBox \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qmessagebox.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QListWidget \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qlistwidget.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qlistview.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qstyleoption.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qvalidator.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qregularexpression.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qslider.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qabstractslider.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qstyle.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qtabbar.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qrubberband.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QTextEdit \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qtextedit.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtextdocument.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtextoption.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtextcursor.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qtextformat.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtGui/qpen.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QBoxLayout \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qboxlayout.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qlayout.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qgridlayout.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QSharedDataPointer \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QString \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QUrl \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QVariant \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QVector \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QObject \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/QSslConfiguration \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/qsslsocket.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/qsslerror.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qcryptographichash.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qdatetime.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/qssl.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QFlags \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QMetaType \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/QNetworkRequest \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/QNetworkReply \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QIODevice \
		../../Resources/Qt/5.14.1/gcc_64/include/QtNetwork/QSslError \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QJsonDocument \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qjsondocument.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qjsonvalue.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QJsonObject \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qjsonobject.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QJsonArray \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qjsonarray.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QFileInfo \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qfileinfo.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QDir \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qdir.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QProgressBar \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/qprogressbar.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QDateTime \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QSaveFile \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qsavefile.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QDebug \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QLocale \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/QXmlStreamReader \
		../../Resources/Qt/5.14.1/gcc_64/include/QtCore/qxmlstream.h \
		MainWindow.h \
		../../Resources/Qt/5.14.1/gcc_64/include/QtWidgets/QWizard \
		FEBioStudioUpdater.h \
		../FEBioStudio/XML/XMLWriter.h \
		../FEBioStudio/MathLib/math3d.h \
		../FEBioStudio/MathLib/mat3d.h \
		../FEBioStudio/MathLib/mat3d.hpp \
		../FEBioStudio/FSCore/color.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

