/*This file is part of the FEBio Studio source code and is licensed under the MIT license
listed below.

See Copyright-FEBio-Studio.txt for details.

Copyright (c) 2021 University of Utah, The Trustees of Columbia University in
the City of New York, and others.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.*/
#include "PLYExport.h"
#include <GeomLib/GObject.h>
#include <GeomLib/GModel.h>
#include <FEMLib/FSProject.h>
using namespace Post;

class PLYFile
{
public:
	PLYFile(FILE* fp) : m_fp(fp) { 
		m_writeBinary = true; 
		m_writeColor = true;
	}

	bool Write(FEPostModel& fem, const CColorMap& tex);

private:
	FILE* m_fp;
	bool	m_writeBinary;
	bool	m_writeColor;
};

PLYExport::PLYExport() { }

PLYExport::~PLYExport(void) { }

void PLYExport::SetColorMap(const CColorMap& tex)
{
	m_tex = tex;
}

bool PLYExport::Save(FEPostModel& fem, const char* szfile)
{
	FILE* fp = fopen(szfile, "wb");
	if (fp == 0) return false;

	PLYFile ply(fp);
	bool b = ply.Write(fem, m_tex);

	fclose(fp);

	return b;
}

bool PLYFile::Write(FEPostModel& fem, const CColorMap& tex)
{
	FEState* state = fem.CurrentState();
	FSMesh* pm = state->GetFEMesh();
	int verts = pm->Nodes();
	int faces = pm->Faces();

	
	// write the header
	fprintf(m_fp, "ply\n");
	if (m_writeBinary) fprintf(m_fp, "format binary_little_endian 1.0\n");
	else fprintf(m_fp, "format ascii 1.0\n");
	fprintf(m_fp, "comment generated by FEBio Studio\n");
	fprintf(m_fp, "element vertex %d\n", verts);
	fprintf(m_fp, "property float x\n");
	fprintf(m_fp, "property float y\n");
	fprintf(m_fp, "property float z\n");
	if (m_writeColor)
	{
		fprintf(m_fp, "property uchar red\n");
		fprintf(m_fp, "property uchar green\n");
		fprintf(m_fp, "property uchar blue\n");
	}
	fprintf(m_fp, "element face %d\n", faces);
	fprintf(m_fp, "property list uchar int vertex_indices\n");
	fprintf(m_fp, "end_header\n");

	// calculate nodal colors
	std::vector<GLColor> col(verts, GLColor(0, 0, 0));
	if (m_writeColor)
	{
		for (int i = 0; i < faces; ++i)
		{
			FSFace& f = pm->Face(i);
			for (int j = 0; j < f.Nodes(); ++j)
			{
				col[f.n[j]] = GLColor::White(); // TODO: This used to map the face texture values to colors
			}
		}
	}

	if (m_writeBinary)
	{
		// write the vertices
		for (int i = 0; i < verts; ++i)
		{
			FSNode& n = pm->Node(i);
			vec3f r = to_vec3f(n.r);
			float f[3] = { r.x, r.y, r.z };
			fwrite(f, 3, sizeof(float), m_fp);
			if (m_writeColor)
			{
				unsigned char c[3] = { col[i].r, col[i].g, col[i].b };
				fwrite(c, 3, sizeof(unsigned char), m_fp);
			}
		}

		// write the faces
		for (int i = 0; i < faces; ++i)
		{
			FSFace& f = pm->Face(i);
			unsigned char nf = (unsigned char)f.Nodes();
			fwrite(&nf, 1, sizeof(unsigned char), m_fp);
			int* n = f.n;
			fwrite(n, nf, sizeof(int), m_fp);
		}
	}
	else
	{
		// write the vertices
		for (int i = 0; i < verts; ++i)
		{
			FSNode& n = pm->Node(i);
			vec3f r = to_vec3f(n.r);
			if (m_writeColor)
			{
				unsigned char c[3] = { col[i].r, col[i].g, col[i].b };
				fprintf(m_fp, "%g %g %g %d %d %d\n", r.x, r.y, r.z, c[0], c[1], c[2]);
			}
			else fprintf(m_fp, "%g %g %g\n", r.x, r.y, r.z);
		}

		// write the faces
		for (int i = 0; i < faces; ++i)
		{
			FSFace& f = pm->Face(i);
			int nf = f.Nodes();
			int* n = f.n;
			switch (nf)
			{
			case 3: fprintf(m_fp, "3 %d %d %d\n", n[0], n[1], n[2]); break;
			case 4: fprintf(m_fp, "4 %d %d %d %d\n", n[0], n[1], n[2], n[3]); break;
			}
		}
	}

	return true;
}