name: CI - macOS Push

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - febiostudio3
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  get_sdk_version:
    runs-on: ubuntu-latest
    outputs:
      sdk_version: ${{ steps.get_sdk_version.outputs.sdk_version }}
    steps:
      - id: get_sdk_version
        uses: febiosoftware/febio-workflows/.github/actions/get-sdk-version.yml@plugin
  call_workflow:
    needs: get_sdk_version
    uses: febiosoftware/febio-workflows/.github/workflows/macos-reusable-push.yml@plugin
    with:
      package-name: febio-studio
      requires-sdk: true
      post-build: true
      python-module: false
      sdk-version: ${{ needs.get_sdk_version.outputs.sdk_version }}
    secrets: inherit
