name: CI - macOS Pull Request
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - 'ci/**'
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/macos-reusable-pull-request.yml@develop
    with:
      package-name: febio-studio
      requires-sdk: true
      sdk-config: |
        {
          "sdk_path": "develop",
          "version": "v4.6",
        }
    secrets: inherit
