name: CI - macOS Push

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - febiostudio3
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  get_sdk_version:
    runs-on: ubuntu-latest
    outputs:
      sdk_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout FEBio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: FEBio
          repository: febiosoftware/FEBio
          ref: develop

      - name: Extract SDK version
        id: get_version
        run: |
          major=$(grep '#define FE_SDK_MAJOR_VERSION' path/to/header.h | awk '{print $3}')
          minor=$(grep '#define FE_SDK_SUB_VERSION' path/to/header.h | awk '{print $3}')
          patch=$(grep '#define FE_SDK_SUBSUB_VERSION' path/to/header.h | awk '{print $3}')
          echo "version=$major.$minor.$patch" >> $GITHUB_OUTPUT

      - run: echo "Version is ${{ steps.get_version.outputs.version }}"
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/macos-reusable-push.yml@plugin
    with:
      package-name: febio-studio
      requires-sdk: true
      post-build: true
      python-module: false
      sdk-version: ${{ needs.get_sdk_version.outputs.sdk_version }}
    secrets: inherit
